---
title: "Data import"
output: github_document
---

```{r setup}
library(tidyverse)
library(dplyr)
library(readxl)
library(ggplot2)
library(p8105.datasets)
library(patchwork)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r}

data_files = 
  tibble(
    path = list.files(path = "./data", full.names = FALSE)
) %>%
  mutate(
    data = map(.x = str_c("./data/", path), ~ read_csv(.x))) %>% 
  unnest(data) %>%
  separate(path, into = c("arm", "subject_id", "csv")) %>%
  select(-csv) %>% 
  pivot_longer(
    cols = week_1:week_8,
    names_to = "week",
    names_prefix = "week_",
    values_to = "observation"
  ) %>% 
  mutate(
    arm = recode(arm, "con" = "Control", "exp" = "Experimental")) 
data_files


```


```{r}
plot_data = data_files %>% 
  ggplot(aes(x = week, y = observation, group = subject_id, color = subject_id)) + 
  geom_point(alpha = 0.5) +
  geom_line() +
  facet_grid( ~ arm) +
  labs(
    title = "Observations over Time by Subject",
    x = "Week",
    y = "Observation"
  ) + 
  theme(plot.title = element_text(hjust = 0.5))
  
plot_data


```
Comment:
The observation values are increasing in the experiment group during the study period. By contrast, the observation value in control group is steady and lower compared to experiment gourp.

```{r}
set.seed(10)
iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))


```




```{r}
iris_with_missing = iris_with_missing %>%
  janitor::clean_names() 
clean_data = function(x){
  
  if (is.numeric(x)){
    
    x = replace_na(x, mean(x, na.rm = TRUE))
    
  } else if (is.character(x)){
    
    x = replace_na(x, "virginica")
  }
}
iris_cleaned = map(iris_with_missing, clean_data) %>% 
  as_tibble()


```




```{r}



```




```{r}



```
